README.md

Links to resources have been out of date since https://github.com/hackmdio/codimd-container/commit/d9bef26b44f45878f30e2ace0d3fee2bc6da799e. This PR will correct them.

Update links to resources in README

---

alpine/Dockerfile
debian/Dockerfile

We just introduced fullversion support in CodiMD. This allows us
to inform all clients about every update of a container.
This patch adds some container specific tricks to keep the current
commit and repository available for this fullversion script, so whenever
someone uses those Dockerfiles to build a container, the source URL for
the CodiMD from this container is correct.
https://github.com/hackmdio/codimd/pull/991
https://github.com/hackmdio/codimd/commit/bcc914a7735290b86e0df428aed75dabdf9f1eca

Add implementation to mime fullversion support

---

docker-compose.yml

We renamed all internal paths to `/codimd`. There were some changes 
missing in the `docker-compose.yml`.
This patch adds those changes so whenever someone tries to use the 
compose file, they'll use the right paths.
Fixes #15

Fix volumes after rename

---

resources/docker-entrypoint.sh

A missing space in line 4 broke some important functionality for the
entrypoint script. Additionally in order to find further problems,
running shellcheck was used to find some other minor issues which are
fixed in this patch as well.
report: https://mastodon.r3pek.org/@r3pek/102192565825972468

Fix entrypoint script

---

docker-compose.yml

`/codimd/tmp` isn't used anymore for quite a while. We use the system
temp directory these days. This patch updates them and gives a larger
size to the tmpfs as it might be used to cache updates depending on the
upload provider user.

Update tmpfs definitions

---

alpine/Dockerfile
debian/Dockerfile

I had some issues when migrating from a docker-based environment to a native deployment due to missiond db-migrations. Therefor the docker-container now runs `npm start` (which applies migrations) instead of `node app.js`. 
The current behaviour would also break when upgrading tu 2.0 because of codimd/server#324 .

run npm start instead of node app.js

---

resources/config.json

Defaulting to imgur as file upload is misleading: the CodeMD documentation says that "filesystem" is the default for "imageUploadType".
That's a security issue. Anyone starting this container would expect file upload to work this way, and not send any private data to imgur or any random website.

Security issue: data leak to imgur

---

.github/workflows/test.yml
README.md
alpine/Dockerfile
debian/Dockerfile
docker-compose.yml
resources/config.json
resources/docker-entrypoint.sh
tools/tagging.sh

To prepare for the rename, I replaced every occurrence of codimd with
hedgedoc.
There were still some stray hackmd references, so I replaced them as
well.
I removed the kubernetes instructions, since they were referring to
a helm chart that does not exist anymore.
There are two references to hackmd left. The first one is in the
migration guide from hackmd-docker to hedgedoc-container. The other one
is in a migration guide that points to
https://github.com/hackmdio/migration-to-0.5.0. Since this repository
wasn't forked (and there's no license attached), I left the reference as
is.

Rename HackMD and CodiMD to HedgeDoc

---

renovate.json

This patch should make sure we don't introduce unexpected breaking
changes into our setup and instead for every upstream upgrade get a new
renovate pull request.

Pin digists of base images

---

renovate.json

This patch adds sign-offs to the renovatebot commits and allows them to
be automatically merged to reduce maintenance work.

Extend renovatebot config to automerge digests

---

docker-compose.yml
renovate.json

This patch should fix the pin-rebuild-pin loop, that appears due to each
change in the repository resulting in a new image build, which results
in a new pin in the docker-compose file, which results in a merge, that
triggers a new build.
Instead this patch excludes the `docker-compose.yaml` from pinning and
solves the issue.

Fix pin-rebuild-pin loop

---

.github/workflows/nightly.yml

Create and push a docker image based on `hedgedoc/hedgedoc@master` to `quay.io/hedgedoc/hedgedoc:nightly-{alpine,debian}`.

Publish nightly docker images

---

resources/config.json

Because of a bug in sequelize, the hardcoded name of the database in config.json was used with mysql/mariadb databases. This commit removes all content from config.json, so environment variables are always used. The file itself must still exist, as HedgeDoc does not start without a config file.
For details see https://github.com/hedgedoc/container/issues/136#issuecomment-747072862
Closes #136

Remove all content from config.json

---

alpine/Dockerfile
debian/Dockerfile

This improves caching and readability without compromising the final image size.
I wasn't sure what was going on with the `yarn install` commands, so I tried to simplify it.
It helped making the image smaller, by removing the dev dependencies from the final image.

Split dockerfiles into stages

---

README.md

Due to changed default database credentials and database name in
`docker-compose.yml`, a previous installation needs to be migrated in
order to work with the new defaults.
Fixes #141.

Add database migration hints for 1.6 -> 1.7 upgrade (fixes #141)

---

README.md

To prevent issues like #142, I've added some more information to the hackmd migration guide.
I also took the opportunity to remove "it's just" and "it's easy" from the text.

Point to HedgeDoc release notes in hackmd section

---

alpine/Dockerfile
debian/Dockerfile
tests/chore/startContainer.sh

This patch should fix current failing builds by adding a 30 seconds
delay between the container starting and the tests starting to run, so
that database migrations and alike can take place.

Fix tests by introducing a delay

---

alpine/Dockerfile
debian/Dockerfile
resources/.sequelizerc
resources/docker-entrypoint.sh
tests/version.sh

This PR removes the .sequelizerc and calls to sequelize-cli as they are not necessary anymore with 1.8.0.
Also fixed a typo in the tests script.

Remove sequelize from entrypoint script and Dockerfile

---

.github/workflows/release.yml
renovate.json

This patch enables renovate to notice new hedgedoc releases and
automatically provide a PR that updates the hedgedoc release version.
This was implemented using the regex-manager that allows to parse
strings and extract the required values for datasource, versioning
schema and project name in order to have them handled by renovatebot.
Reference:
https://docs.renovatebot.com/modules/manager/regex/

Implement automatic version management for releases

---

README.md

The instructions have been migrated to https://docs.hedgedoc.org/setup/docker/
To reduce confusion, they should not be duplicated here.

Update README to point to docs.hedgedoc.org

---

alpine/Dockerfile
debian/Dockerfile
resources/docker-entrypoint.sh

Currently the entrypoint script parses the database URL configuration
string in order to extract the remote location and waits for the
database to be available.
This patch removes this logic and also removes `dockerize`, which was
used to wait for the connection. However, this change should not be
merged without the changes introduced in a commit on the main
application, that implements an own connection retry mechanism.
Reference:
https://github.com/hedgedoc/hedgedoc/pull/1228

Remove dockerize and entrypoint-script parsing

---

alpine/Dockerfile
debian/Dockerfile

This PR removes the separate `basebuilder` step and speeds up the build a bit by not removing the `node_modules` folder in between `yarn install`s.

Dockerfile cleanups

---

alpine/Dockerfile
debian/Dockerfile
resources/healthcheck.mjs

This ports the healthcheck from https://github.com/hedgedoc/hedgedoc/pull/1228.
There was a short discussion in the dev chat, whether we want to include this by default.
The healthcheck seems to delay Traefik adding the container as a backend, but with the interval set to 5 seconds, this doesn't seem too big of a deal.
Also, as we currently don't recommend nor document a setup with Traefik, we can assume that someone who is using Traefik can also disable the healthcheck if they are bothered by it.

Add simple healthcheck

---

alpine/Dockerfile
debian/Dockerfile
resources/docker-entrypoint.sh

Since some people serve their static data by uploads directory, unhandy
to set the permissions of the upload directory to 0700 by default.
In order to allow everyone to set the permissions themselves, an option
`UPLOADS_MODE` is introduced that will allow to define the default mode
set to the directory.
Fixes #25

Add option to change permissions on upload dir

---

alpine/Dockerfile
debian/Dockerfile

This creates the hedgedoc user earlier as a workaround for https://github.com/GoogleContainerTools/kaniko/issues/1456.
This fix has a small impact and allow other people to build with kaniko (often used in gitlab).

Fix chown issue on kaniko

---

resources/healthcheck.mjs

This patch adds a custom user-agent to the healthcheck script to make it
more obvious in the logs where these requests come from. This was
requested by someone in the support chat.
It changes the regular log message from:
```
2021-12-11T14:12:03.339Z info: 	127.0.0.1 - - [11/Dec/2021:14:12:03 +0000] "GET /status HTTP/1.1" 200 266 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
```
To a more intuitive and readable user-agent:
```
2021-12-11T14:01:46.105Z info: 	127.0.0.1 - - [11/Dec/2021:14:01:46 +0000] "GET /status HTTP/1.1" 200 266 "-" "hedgedoc-container-healthcheck/1.0"
```
References:
https://matrix.to/#/!oaRMJImPLfUnnXzwnN:shivering-isles.com/$p-1lIoZ3HJG7nCEedeE16GjBPnkRT8jvERGGJ2dDrpk?via=matrix.org&via=kif.rocks&via=envs.net

feat(healthcheck): Add user-agent to healthcheck script

---

alpine/Dockerfile
debian/Dockerfile

We switched to a sqlite3 package that does not provide prebuilt binaries.
This PR adds the dependencies required to build sqlite3 to the build-container.

Add missing build dependencies for sqlite3

---

resources/utf8.cnf

Since MariaDB 10.6 the 'utf8' character set is an alias for 'utf8mb3'.
This seems to trip up something, and HedgeDoc can't connect to the database anymore.
This PR changes the character set to 'utf8mb4', which is the "real" UTF-8 charset for MariaDB.
It should be backwards compatible with older *MariaDB versions*, the charset exists for a long time.
This will probably **break** existing *databases*, as the data in the tables needs to be manually converted (see https://mathiasbynens.be/notes/mysql-utf8mb4).
References:
https://mariadb.com/kb/en/upgrading-from-mariadb-105-to-mariadb-106/#character-sets
https://mariadb.com/kb/en/mariadb-1061-release-notes/#character-sets
https://mathiasbynens.be/notes/mysql-utf8mb4

Use utf8mb4 character set in MariaDB config

---

.github/workflows/nightly.yml
.github/workflows/release.yml

This reverts commit ce0a86b190346c762b94b10edf7cee354c872778 in favor of https://github.com/hedgedoc/container/pull/398

Revert "feat: add armv7 and arm64 platforms"

---

alpine/Dockerfile
debian/Dockerfile
resources/healthcheck.mjs

This PR changes the endpoint for the healthcheck from the more resource-hungry /status endpoint to /_health. It also decreases the interval to only check every 15 seconds instead of every 5 seconds to further reduce the load for the machine while keeping a reasonable interval.
This requires hedgedoc/hedgedoc#3450 as a pre-requisite

Use /_health endpoint for healthcheck and decrease interval

---

alpine/Dockerfile
debian/Dockerfile

Use `apk add` command with `--no-cache` instead of an additional `apk update`, and remove the additional `apt-get clean`, which was also in the wrong place.
This change will ensure that no temporary files are left in the Docker images and remove unnecessary steps from the Dockerfiles.
Reference:
- https://docs.docker.com/build/building/best-practices/#apt-get
> Official Debian and Ubuntu images [automatically run `apt-get clean`](https://github.com/moby/moby/blob/03e2923e42446dbb830c654d0eec323a0b4ef02a/contrib/mkimage/debootstrap#L82-L105),so explicit invocation is not required.

Improve apk & apt pkg mgmt tool usage in Dockerfiles
